language: csharp
solution: SendGrid/SendGrid.sln
env:
  global:
    - secure: "S6rHgh05/IRe/UjhObIK/IX4O2B9dXgvpKln2bM1trJcZsO1uRN74UjQ22ExKQBpAfKwxG9yNOdomxoIn1/WhwQfmwSKrnegN86l09aNzKSSdoK7wt1pfJz952/FO/a4jV/e1p3E5g2hEpopG+KLmaipwE+qmlQrEaZUgZLx/mI="
install:
- nuget restore SendGrid/SendGrid.sln
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=BuildNet45 SendGrid/SendGrid.sln
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe SendGrid/Tests/bin/BuildNet45/Tests.dll
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe SendGrid/UnitTest/bin/Release/UnitTest.dll
notifications:
  hipchat:
    rooms:
      secure: T8r/eNzevZXJDmSK7ZKG+t/Vx0cENHIMWVuKbt3RSYbXl6QsWv8UTPamFSkLP0zbcCyGQ7d+QKaEc18ffCtiBV9MXPy8Q1XFGzKxr5/GnwMx4p0ArTqbFLCyl3JuXBmCGouWG+ulb9eOGUFc6L/4p2cwAfXf2oTcXYqosBnfoHg=
    template:
    - '<a href="https://travis-ci.org/%{repository}/builds/%{build_id}">%{repository}
      Build %{build_number}</a> on branch <i>%{branch}</i> by %{author}: <strong>%{message}</strong>
      <a href="https://github.com/%{repository}/commits/%{commit}">View on GitHub</a>'
    format: html
