language: csharp
solution: SendGrid.sln

matrix:
  include:
    - dotnet: 1.0.0-preview2-003121
      os: linux
      dist: trusty
      mono: none
      env: DOTNETCORE=1
    - mono: latest

env:
  matrix:
    secure: KJrQ+NfmzlgCSXRyqeAMDGZUG6GO4/+xk1T0wGy1BgVz8seo/fDWL8osWEljB4Sj05sfFj7CM+rociwL6sdVyqCiHbCAM7XuHs58D+4Tlh5pGHL+G1qOl65/pDl0ulq+M7PwDxHPZ60/oyH2a16t5jtD9e4W31y2fXzEbHGLHXg=

install:
  - if [ -z "${DOTNETCORE}" ]; then nuget restore SendGrid.sln; fi
  - if [ -z "${DOTNETCORE}" ]; then nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner; fi

before_script:
- mkdir prism/bin
- export PATH=$PATH:$PWD/prism/bin/
- ls -la
- ./prism/prism.sh
- nohup prism run -s https://raw.githubusercontent.com/sendgrid/sendgrid-oai/master/oai_stoplight.json &

script:
  - if [ -n "${DOTNETCORE}" ]; then mkdir bla && cd bla && dotnet new && time dotnet restore && dotnet run && dotnet test; fi
  - if [ -z "${DOTNETCORE}" ]; then mkdir bla && cd bla && dotnet new && time dotnet restore; fi
  - if [ -z "${DOTNETCORE}" ]; then xbuild /p:Configuration=Release SendGrid.sln; fi
  - if [ -z "${DOTNETCORE}" ]; then ./testrunner/NUnit.Runners.3.2.0/tools/nunit-console.exe ./UnitTest/bin/Release/UnitTest.dll; fi

notifications:
  hipchat:
    rooms:
      secure: T8r/eNzevZXJDmSK7ZKG+t/Vx0cENHIMWVuKbt3RSYbXl6QsWv8UTPamFSkLP0zbcCyGQ7d+QKaEc18ffCtiBV9MXPy8Q1XFGzKxr5/GnwMx4p0ArTqbFLCyl3JuXBmCGouWG+ulb9eOGUFc6L/4p2cwAfXf2oTcXYqosBnfoHg=
    template:
    - '<a href="https://travis-ci.org/%{repository}/builds/%{build_id}">%{repository}
      Build %{build_number}</a> on branch <i>%{branch}</i> by %{author}: <strong>%{message}</strong>
      <a href="https://github.com/%{repository}/commits/%{commit}">View on GitHub</a>'
    format: html
